cluster.name: elk-cluster
node.name: ${HOSTNAME}

network.host: 0.0.0.0
#network.publish_host: _eth0_
#network.bind_host: [_local_, _eth0_]

http.port: 9200
transport.tcp.port: 9300

discovery.zen.ping.unicast.hosts: ["127.0.0.1", "[::1]"]

# (master_eligible_nodes / 2) + 1
discovery.zen.minimum_master_nodes: 1

bootstrap.memory_lock: true

#index.mapper.dynamic: false

http.cors.enabled: true
http.cors.allow-origin: "*"

indices.fielddata.cache.size: 20%

path.repo: ["/usr/share/elasticsearch/backups"]