cluster.name: elk-cluster
node.name: node1

network.host: 0.0.0.0
#network.publish_host: _eth0_
#network.bind_host: [_local_, _eth0_]

http.port: 9200
transport.tcp.port: 9300

discovery.zen.ping.unicast.hosts: ["127.0.0.1", "[::1]"]

# (master_eligible_nodes / 2) + 1
discovery.zen.minimum_master_nodes: 1

bootstrap.memory_lock: true

#index.mapper.dynamic: false

http.cors.enabled: true
http.cors.allow-origin: "*"

indices.fielddata.cache.size: 20%

xpack.ssl.key:                     ${ES_HOME}/config/ssl/node1.key
xpack.ssl.certificate:             ${ES_HOME}/config/ssl/node1.crt
xpack.ssl.certificate_authorities: [ "${ES_HOME}/config/ssl/ca.crt" ]

# enable tls/ssl connection
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true

# disable ca verification
xpack.ssl.verification_mode: none
xpack.ssl.client_authentication: none

xpack.security.audit.enabled: true
xpack.security.audit.outputs: [ index ]
xpack.security.audit.index.events.exclude: [ access_granted, authentication_success ]
xpack.security.audit.logfile.events.exclude: [ access_granted, authentication_success ]

xpack.monitoring.enabled: false
xpack.graph.enabled: false
xpack.watcher.enabled: false