cluster.name: elk-cluster
node.name: ${HOSTNAME}

network.host: 0.0.0.0
network.publish_host: ${network.publish_host}
transport.publish_port: ${transport.publish_port}
#network.bind_host: [_local_, _eth0_]

http.port: 9200
transport.tcp.port: 9300

discovery.zen.ping.unicast.hosts: ${discovery.zen.ping.unicast.hosts}

# (master_eligible_nodes / 2) + 1
discovery.zen.minimum_master_nodes: ${discovery.zen.minimum_master_nodes}

bootstrap.memory_lock: true

#index.mapper.dynamic: false

http.cors.enabled: true
http.cors.allow-origin: "*"

indices.fielddata.cache.size: 20%

path.repo: ["/usr/share/elasticsearch/backups"]