version: "2"

services:

  elasticsearch:
    image: ${REGISTRY_URL}/elasticsearch:${IMAGE_TAG}
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - ${ES_DATA_HOME}:/usr/share/elasticsearch/data
    - ${ES_BACKUP_HOME}:/usr/share/elasticsearch/backups
    environment:
    - "discovery.zen.ping.unicast.hosts=${ES_MASTER_NODE_HOST}"
    - "discovery.zen.minimum_master_nodes=${ES_MINIMUM_MASTER_NODE}"
    - "transport.publish_port=${ES_TRANSPORT_PORT}"
    restart: "unless-stopped"

  nginx:
    image: ${REGISTRY_URL}/nginx-elk:0.1
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - elasticsearch
    extra_hosts:
    - kibana:127.0.0.1
    - logstash:127.0.0.1
    ports:
    #- 9200:9200     # elasticsearch
    - ${ES_TRANSPORT_PORT}:9300     # elasticsearch
    volumes:
    - ${SSL_DIR}/server-cert.pem:/etc/nginx/ssl/nginx.crt
    - ${SSL_DIR}/server-key.pem:/etc/nginx/ssl/nginx.key
    - ${SSL_DIR}/ca.pem:/etc/nginx/ssl/ca.crt
    restart: "unless-stopped"

volumes:
  esdata:
  esbackup: