version: "2"

services:

  elasticsearch:
    build: elasticsearch
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - esdata:/usr/share/elasticsearch/data
    - ${ES_BACKUP_HOME}:/usr/share/elasticsearch/backups
    environment:
    - "discovery.zen.ping.unicast.hosts=${ES_MASTER_NODE_HOST}"
    - "discovery.zen.minimum_master_nodes=${ES_MINIMUM_MASTER_NODE}"
    - "transport.publish_port=${ES_TRANSPORT_PORT}"

  nginx:
    build: nginx
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - elasticsearch
    extra_hosts:
    - kibana:127.0.0.1
    - logstash:127.0.0.1
    ports:
    #- 9200:9200     # elasticsearch
    - ${ES_TRANSPORT_PORT}:9300     # elasticsearch

volumes:
  esdata:
  esbackup: