version: "2"

services:

  elasticsearch:
    image: ${REGISTRY_URL}/elasticsearch:${IMAGE_TAG}
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - ${ES_DATA_HOME}:/usr/share/elasticsearch/data
    - ${ES_BACKUP_HOME}:/usr/share/elasticsearch/backups
    environment:
    - "discovery.zen.ping.unicast.hosts=${ES_MASTER_NODE_HOST}"
    - "discovery.zen.minimum_master_nodes=${ES_MINIMUM_MASTER_NODE}"
    - "transport.publish_port=${ES_TRANSPORT_PORT}"
    ports:
    - ${ES_TRANSPORT_PORT}:9300     # elasticsearch

volumes:
  esdata:
  esbackup: