version: "2"

services:
  elasticsearch:
    image: ${REGISTRY_URL}/elasticsearch
    extends: 
      file: common-services.yml
      service: elasticsearch
    volumes:
    - esdata:/opt/elasticsearch/data

  logstash:
    image: ${REGISTRY_URL}/logstash
    extends: 
      file: common-services.yml
      service: logstash
    ports: 
    - 5000:5000
    - 5000:5000/udp
    - 5043:5043

  kibana:
    image: ${REGISTRY_URL}/kibana
    extends: 
      file: common-services.yml
      service: kibana

  nginx:
    image: ${REGISTRY_URL}/nginx-elk
    extends: 
      file: common-services.yml
      service: nginx
    depends_on: 
    - kibana
    - elasticsearch
    - logstash
    ports:
    - 5601:5601
    - 9200:9200

#   headplug:
#     extends: 
#       file: common-services.yml
#       service: headplug
#     ports:
#     - 9100:9100

volumes:
  esdata:
  fbdata: