version: "2"

services: 
  curator:
    build: curator
    network_mode: "service:elasticsearch"
    volumes: 
    - ./curator/actions:/usr/share/curator
    environment: 
    - SNAPSHOT_REPOSITORY
    depends_on:
    - elasticsearch